style:
  - changed-files:
    -any-glob-to-any-files: "**/*.css"

docs:
  - changed-files:
    - any-glob-to-any-files: "**/*.md"

feature:
  - head-branch: 'feat/*'

hotfix:
  - head-branch: 'fix/*'

release:
  - base-branch: 'main'
